# .github/stale.yml
stale:
  daysUntilStale: 60
  daysUntilClose: 7
  staleLabel: "stale"
  exemptLabels:
    - "pinned"
    - "security"
  markComment: >
    This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
