runtime: python39
entrypoint: gunicorn -b :$PORT procounsel.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "procounsel.settings"

handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto


# 👇 Add this to skip large/unneeded folders
skip_files:
  - ^env/.*            # your virtual environment
  - ^venv/.*           # or other virtual env names
  - ^node_modules/.*   # if present
  - ^__pycache__/.*    # compiled python files
  - ^\.git/.*          # git repo
  - ^\.idea/.*         # PyCharm or IDE files
  - ^\.vscode/.*       # VS Code config
  - ^.*\.pyc           # compiled Python files
  - ^\.DS_Store        # MacOS metadata