runtime: python39
entrypoint: gunicorn -b :$PORT procounsel.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "procounsel.settings"

handlers:
- url: /static
  static_dir: staticfiles

- url: /.*
  script: auto